name: asmt

container:
  - base:

      - docker.qe.aerospike.com/build/aerospike-server:arm-centos-7
      - docker.qe.aerospike.com/build/aerospike-server:arm-rhel-8
      - docker.qe.aerospike.com/build/aerospike-server:arm-debian-10
      - docker.qe.aerospike.com/build/aerospike-server:arm-debian-11
      - docker.qe.aerospike.com/build/aerospike-server:arm-ubuntu-18.04
      - docker.qe.aerospike.com/build/aerospike-server:arm-ubuntu-20.04


build:
  - name: default
    script:
      - make
      - make $PKG
    artifact:
      - target/bin/*
      - target/packages/*
