name: Build ASMT

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: configure
        run: sudo apt-get install make gcc libc6-dev zlib1g-dev
      - name: build
        run: make
      - name: Archive Binary 
        uses: actions/upload-artifact@v2.2.4
        with: 
          name: asmt
          path: target/bin/asmt
          if-no-files-found: error
      - name: Download Binary
        uses: actions/download-artifact@v2.0.10
        with:
          name: asmt
          path: pkgs
          
            

