name: Build ASMT

on:
  push:
    branches: [ OPS-5275 ]
  pull_request:
    branches: [ OPS-5275 ]
        
jobs:
  buils_atl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ 'centos:7', 'redhat/ubi8', 'debian:8', 'debian:9', 'debian:10' ]
    container:
      image: ${{ matrix.container }}
      options: "--entrypoint /bin/bash"
    steps:
    - name: Install Dependencies (centos:7)
      run: |
        yum install -y dnf-plugins-core
        yum-config-manager --enable powertools
        yum install -y make gcc zlib-devel zlib-static git rpm-build
      if: matrix.container == 'centos:7'
    - name: Install Dependencies (redhat-8)
      run: |
        yum install -y dnf-plugins-core
        yum config-manager --set-enable powertools
        yum install -y make gcc zlib-devel zlib-static git rpm-build
      if: matrix.container == 'redhat/ubi8'
    - name: Install Dependencies (Debian)
      run: |
        apt-get -y update
        apt-get -y install make gcc libc6-dev zlib1g-dev git
      if: |
        matrix.container == 'debian:8' || matrix.container == 'debian:9' || matrix.container == 'debian:10'
    - name: Clone Source
      run: git clone --branch OPS-5275 https://github.com/aerospike/asmt.git
    - name: buils asmt
      working-directory: ./asmt
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
        make asmt rpm
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: asmt-${{ env.REV }}-${{ env.OS }}
        path: /__w/asmt/asmt/asmt/target/packages/asmt-*
        if-no-files-found: error
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'ubuntu-18.04' ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Dependencies (Ubuntu-latest)
      run: sudo apt-get install make gcc libc6-dev zlib1g-dev
      if: matrix.os == 'ubuntu-20.04'
    - name: Install Dependencies (Ubuntu-latest)
      run: sudo apt-get install make gcc libc6-dev zlib1g-dev
      if: matrix.os == 'ubuntu-18.04'
    - name: Get Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout ACT
      uses: actions/checkout@v2
      with:
        repository: citrusleaf/qe-docker
        token: ${{ secrets.ASMT_PAT }}
        ref: master
        path: qe-docker
    - name: Set env
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
        ls -la .
        ls -la ./qe-docker
    - name: build
      run: make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with: 
        name: asmt-${{ env.REV }}-${{ env.OS }}
        path: target/packages
        if-no-files-found: error

