name: Build ASMT

on:
  push:
    branches: [ OPS-5275 ]
  pull_request:
    branches: [ OPS-5275 ]
        
jobs:
  debug:
    runs-on: ubuntu-latest
    container: { image: waffleimage/centos7 }
    steps:  
    - run: yum install -y dnf-plugins-core
    - run: yum-config-manager --enable powertools
    - run: yum install -y make gcc zlib-devel zlib-static git
    - run: git clone --branch OPS-5275 https://github.com/aerospike/asmt.git
    - run: cd asmt & ls -la

    
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'ubuntu-18.04' ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Dependencies (Ubuntu-latest)
      run: sudo apt-get install make gcc libc6-dev zlib1g-dev
      if: matrix.os == 'ubuntu-20.04'
    - name: Install Dependencies (Ubuntu-latest)
      run: sudo apt-get install make gcc libc6-dev zlib1g-dev
      if: matrix.os == 'ubuntu-18.04'
    - name: Get Sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Checkout ACT
      uses: actions/checkout@v2
      with:
        repository: citrusleaf/qe-docker
        token: ${{ secrets.ASMT_PAT }}
        ref: master
        path: qe-docker
    - name: Set env
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
        ls -la .
        ls -la ./qe-docker
    - name: build
      run: make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with: 
        name: asmt-${{ env.REV }}-${{ env.OS }}
        path: target/packages
        if-no-files-found: error

