name: Build ASMT

on:
  push:
    branch: [ OPS-5275 ]
  pull_request:
    branch: [ OPS-5275 ]
        
jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04' ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Dependencies (Ubuntu-latest)
      run: sudo apt-get install make gcc libc6-dev zlib1g-dev
      if: matrix.os == 'ubuntu-20.04'
    - name: Get Sources
      uses: actions/checkout@v2
    - name: Fetch repo history
      run: git fetch --prune --unshallow
    - name: Set env
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
    - name: build
      run: make all deb
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.4
      with: 
        name: asmt-${{ env.REV }}-${{ env.OS }}
        path: target/packages
        if-no-files-found: error
