name: Build ASMT

on:
  push:
    branches: [ TOOLS-2226 ]
    tags:
      - '*'
  pull_request:
    branches: [ TOOLS-2226 ]
        
jobs:
  buils_x86_64_debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ 'debian:10', 'debian:11' ]
    container:
      image: ${{ matrix.container }}
      options: "--entrypoint /bin/bash"

    steps:

    - name: Install Dependencies (centos:7)
      run: |
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        yum upgrade -y
        yum install -y dnf-plugins-core
        yum-config-manager --enable powertools
        yum install -y make gcc zlib-devel zlib-static git rpm-build
      if: matrix.container == 'centos:7'

    - name: Install Dependencies (centos:8)
      run: |
        yum upgrade -y
        yum install -y dnf-plugins-core
        yum config-manager --set-enable powertools
        yum install -y make gcc zlib-devel zlib-static git rpm-build
      if: matrix.container == 'centos:8'

    - name: Install Dependencies (Debian)
      run: |
        apt-get -y update
        apt-get -y install make gcc libc6-dev zlib1g-dev git build-essential
      if: |
        matrix.container == 'debian:10' || matrix.container == 'debian:11'

    - name: Clone Source
      run: git clone --branch TOOLS-2226 https://github.com/aerospike/asmt.git

    - name: buils asmt (centos)
      working-directory: ./asmt
      if: matrix.container == 'centos:7' || matrix.container == 'centos:8'
      run: |
        echo "REV=$(make -f pkg/Makefile.rpm print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.rpm print-OS)" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        echo "ARCH=$(make -f pkg/Makefile.rpm print-ARCH)" >> $GITHUB_ENV
        make all rpm

    - name: build asmt (debian)
      working-directory: ./asmt
      if: |
        matrix.container == 'debian:10' || matrix.container == 'debian:11' 
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        echo "ARCH=$(make -f pkg/Makefile.deb print-ARCH)" >> $GITHUB_ENV
        make all deb      

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.1
      with:
        name: asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        path: /__w/asmt/asmt/asmt/target/packages/asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        if-no-files-found: error

  build_x86_64_ubuntu:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'ubuntu-18.04' ]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Install Dependencies
      run: sudo apt-get install make gcc libc6-dev zlib1g-dev
      if: matrix.os == 'ubuntu-20.04'

    - name: Get Sources
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set env
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        echo "ARCH=$(make -f pkg/Makefile.deb print-ARCH)" >> $GITHUB_ENV
        ls -la

    - name: build
      run: make all deb

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with: 
        name: asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        path: target/packages/asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        if-no-files-found: error

  build_arm_ubuntu:
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #container: [ 'arm64v8/ubuntu:bionic', 'arm64v8/ubuntu:focal' ]
    #container:
      #image: ${{ matrix.container }}
      #options: "--entrypoint /bin/bash"
    steps:
      - name: Set up QEMU - arm
        uses: docker/setup-qemu-action@v2.1.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Get Sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #- name: Clone Source
        #run: git clone --branch TOOLS-2226 https://github.com/aerospike/asmt.git

      - name: install depebdencies
        run: |
         sudo apt-get update
         sudo apt-get install make gcc libc6-dev zlib1g-dev
         
      - name: set env
        run: |
          echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
          echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "ARCH=$(make -f pkg/Makefile.deb print-ARCH)" >> $GITHUB_ENV

      - name: build
        run: |
          pwd
          make all deb

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
          path: target/packages/asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
          if-no-files-found: error

  build_arm_debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ 'arm64v8/debian:bullseye', 'arm64v8/ubuntu:buster' ]
    container:
      image: ${{ matrix.container }}
      options: "--entrypoint /bin/bash"
    steps:

    - name: Install Dependencies arm ubuntu
      run: |
        sudo apt-get update
        apt-get -y install make gcc libc6-dev zlib1g-dev git build-essential

    - name: Clone Source
      run: git clone --branch TOOLS-2226 https://github.com/aerospike/asmt.git

    - name: Set env
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        echo "ARCH=$(make -f pkg/Makefile.deb print-ARCH)" >> $GITHUB_ENV
    
    - name: build
      run: make all deb
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        path: target/packages/asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        if-no-files-found: error

  build-on-aarch64:
    runs-on: ubuntu-latest
    name: ci (arm64)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build in arm64 container
        uses: uraimo/run-on-arch-action@v2.3.0
        with:
          arch: aarch64
          distro: ubuntu20.04
          # Install deps into the container. With the token, the container will be cached
          # The image is cached publically like a package
          #githubToken: ${{ github.token }}
          shell: /bin/bash
          install: |
            apt-get -y update
            apt-get -y install make gcc git zlib1g-dev build-essential
  
          run: |
            git config --global --add safe.directory /home/runner/work/asmt/asmt
            pwd
            echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
            echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
            echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
            echo "ARCH=$(make -f pkg/Makefile.deb print-ARCH)" >> $GITHUB_ENV
            make all deb
            
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
          path: target/packages/asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
          if-no-files-found: error            

 
