name: Build ASMT

on:
  push:
    branches: [ TOOLS-2226 ]
    tags:
      - '*'
  pull_request:
    branches: [ TOOLS-2226 ]
        
jobs:
  buils_atl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ 'debian:10', 'debian:11' ]
    container:
      image: ${{ matrix.container }}
      options: "--entrypoint /bin/bash"
    steps:
    - name: Install Dependencies (centos:7)
      run: |
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
        yum upgrade -y
        yum install -y dnf-plugins-core
        yum-config-manager --enable powertools
        yum install -y make gcc zlib-devel zlib-static git rpm-build
      if: matrix.container == 'centos:7'
    - name: Install Dependencies (centos:8)
      run: |
        yum upgrade -y
        yum install -y dnf-plugins-core
        yum config-manager --set-enable powertools
        yum install -y make gcc zlib-devel zlib-static git rpm-build
      if: matrix.container == 'centos:8'
    - name: Install Dependencies (Debian)
      run: |
        apt-get -y update
        apt-get -y install make gcc libc6-dev zlib1g-dev git build-essential
      if: |
        matrix.container == 'debian:10' || matrix.container == 'debian:11'
    - name: Clone Source
      run: git clone --branch TOOLS-2226 https://github.com/aerospike/asmt.git
    - name: buils asmt (centos)
      working-directory: ./asmt
      if: matrix.container == 'centos:7' || matrix.container == 'centos:8'
      run: |
        echo "REV=$(make -f pkg/Makefile.rpm print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.rpm print-OS)" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        echo "ARCH=$(make -f pkg/Makefile.rpm print-ARCH)" >> $GITHUB_ENV
        make all rpm
    - name: build asmt (debian)
      working-directory: ./asmt
      if: |
        matrix.container == 'debian:10' || matrix.container == 'debian:11' 
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        echo "ARCH=$(make -f pkg/Makefile.deb print-ARCH)" >> $GITHUB_ENV
        make all deb      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.1
      with:
        name: asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        path: /__w/asmt/asmt/asmt/target/packages/asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        if-no-files-found: error
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'ubuntu-18.04' ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Dependencies
      run: sudo apt-get install make gcc libc6-dev zlib1g-dev
      if: matrix.os == 'ubuntu-20.04'
    - name: Get Sources
      uses: actions/checkout@v2.5.0
      with:
        fetch-depth: 0
    - name: Set env
      run: |
        echo "REV=$(make -f pkg/Makefile.deb print-REV)" >> $GITHUB_ENV
        echo "OS=$(make -f pkg/Makefile.deb print-OS)" >> $GITHUB_ENV
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
        echo "ARCH=$(make -f pkg/Makefile.deb print-ARCH)" >> $GITHUB_ENV
        ls -la
    - name: build
      run: make all deb
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with: 
        name: asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        path: target/packages/asmt_${{ env.REV }}-1${{ env.OS }}_${{ env.ARCH }}.deb
        if-no-files-found: error
